### ISSUE TITLE
New error on 1.3.3 when watching stream

### ISSUE THREAD

**Issue by Reserton** [Zaarrg/TTVDropBot#20]
Firstly thanks and great work getting the issues fixed so quickly.

However currently 1.3.3 seems to be broken for me at least. Once you choose the channel to watch it gets below error, I have tried the npm and .exe compiled versions and they both do the same thing : 

Setting Video Settings like Quality and Volume...

Watching https://www.twitch.tv/Sykkuno...

(node:35920) UnhandledPromiseRejectionWarning: Error: Evaluation failed: TypeError: Cannot read property 'startsWith' of undefined
    at <anonymous>:57:33
    at Array.filter (<anonymous>)
    at <anonymous>:56:39
    at ExecutionContext._evaluateInternal (S:\RustDropBot\node_modules\puppeteer\lib\cjs\puppeteer\common\ExecutionContext.js:218:19)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async ExecutionContext.evaluate (S:\RustDropBot\node_modules\puppeteer\lib\cjs\puppeteer\common\ExecutionContext.js:107:16)
    at async MapDrops (S:\RustDropBot\src\functions\MapDrops.js:89:5)
    at async CheckProgressCurrentPage (S:\RustDropBot\src\Checks\CheckProgressCurrentPage.js:14:5)
    at async S:\RustDropBot\src\Pages\StreamPage.js:68:9
    at async CurrentProgressEvent (S:\RustDropBot\src\Pages\StreamPage.js:66:5)
    at async StreamPage (S:\RustDropBot\src\Pages\StreamPage.js:54:5)
    at async intrust (S:\RustDropBot\src\Pages\WatchingPage.js:79:13)
(Use `TTVDropBot --trace-warnings ...` to show where the warning was created)
(node:35920) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:35920) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by Zaarrg** [comment]
Just tried to watch the same ch and works fine for me. 

![Screenshot_6](https://user-images.githubusercontent.com/62082797/126051681-7de5cb0c-1e70-4dd4-a92e-4e64b62dd1b7.png)
When its failing the Evaluation with something being undefined this mostly means that the Bot can't get some value from the watching or progress page. Could be a result of the page not loading, data on it not loading etc. So can't actually tell. I think its the progress page not loading active drops... try to go on https://www.twitch.tv/drops/inventory make sure the drop is there under active drops then try to watch it with the bot.

**Comment by Reserton** [comment]
It does it on every stream for me, and the drop is currently 50% on my drops page and works in the old version.

It takes about 2-4 minutes to get the error.

Sykunno is only one with out a complete drop i have online currently.

I have tried Cyr whos drop I have completed and same issue as below : 

![image](https://user-images.githubusercontent.com/1967737/126051749-07df470b-99d2-4a50-9489-4c9b0b3eba1f.png)

**Comment by Zaarrg** [comment]
Use the npm version and go into src/Pages and open Watchingpage.js and change in line 23 `headless: true` to `headless: false`.
Then start the Bot and the Bot wont close Chrome and let u see what is happening. Then when the bot is at `Watching .....` check what is shown on https://www.twitch.tv/drops/inventory. This site should be already opened by the bot. Check if active Drops is shown and the progress of the Drops are shown etc.

Also maybe restart ur pc this could fix the page not properly loading

**Comment by Zaarrg** [comment]
Basicly the Bot doesnt find and active drops on https://www.twitch.tv/drops/inventory
Got this issue while testing like once or twice cause the active drops didn't load. But it should not happen on every drop every time cause the page is pretty much reloaded everytime it checks it...

**Comment by Reserton** [comment]
It is very strange. I will try a reboot.

With headless false it appears to load the page fine. It refreshes it once or twice. However the drop is showing fine on this page.

![image](https://user-images.githubusercontent.com/1967737/126051912-165da047-6307-4fb1-b641-1c4bda450308.png)

**Comment by Zaarrg** [comment]
Hm weird if u dont mind adding some code for debbuging you can go to src/functions and open mapdrops.js and add in line 75 just before `//Filter the Gloabl Drops Out` add 
`console.log(activedrops )`
then restart the bot this should log everthing the bot gets from your twitch inventory

**Comment by Reserton** [comment]
Is it supposed to print the log into the cmd? as it didnt print anything. So if so its either not getting that far or I done it wrong.

My code is 

`            })

            console.log(activedrops )
            //Filter the Gloabl Drops Out
            activedrops = activedrops.filter((item) => {
                return item.url.startsWith('https://www.twitch.tv')
            })
`

**Comment by Zaarrg** [comment]
Open mapdrops.js and take the code from here https://pastebin.com/d4H1QmEX and replaced it just to ctrl +a and replace it with everything frome pastebin. This should log it in the cmd

**Comment by Reserton** [comment]
Very strange.

![image](https://user-images.githubusercontent.com/1967737/126052106-f2934fd5-7e14-4aa2-bb98-28e92d47ee28.png)

**Comment by Zaarrg** [comment]
Ah okay found the issue its the nmplol chestplate it has 2 streamers linked to it and the bot doesnt know it has to look out for drops with two links to watch...
Can u right click in chrome in the twitch inventory page and save the page as and send it to me. Then i can create a quick fix for it cause i dont have nmplol drop in my inventory therefor did not get the error u did

**Comment by Reserton** [comment]
Ah yes. Page attached.

[Twitch.zip](https://github.com/Zaarrg/TTVDropBot/files/6835476/Twitch.zip)

**Comment by Zaarrg** [comment]
Hm i think the twitch folder is missing in ur download, usally chrome saves pages as twitch.html + "html name" folder

**Comment by Reserton** [comment]
Ah yes, I downloaded to a larger folder so didnt notice the folder. Here is full archive.
[TwitchDrops.zip](https://github.com/Zaarrg/TTVDropBot/files/6835482/TwitchDrops.zip)

**Comment by Zaarrg** [comment]
Hm okay seems that the twitch page cant be saved... Can you follow the steps like here https://streamable.com/a4qbxp and then take a screen of whats shown on the right. Would help a lot.

Sry that i have to ask you to do it all but cant recreate the error cause can't get the drop because its offline sadly....

**Comment by Zaarrg** [comment]
Oh and click select the nmplol twitch thing not like i did cyr

**Comment by Reserton** [comment]
<p data-test-selector="DropsCampaignInProgressDescription-hint-text-parent" class="sc-AxirZ fOcBjS">To continue the progress, go to <a class="ScCoreLink-udwpw5-0 FXIKh tw-link" rel="noopener noreferrer" target="_blank" href="/directory/game/Rust?tl=c2542d6d-cd10-4532-919b-3d19f30a768b">a participating live channel</a> including <span><a data-test-selector="DropsCampaignInProgressDescription-two-channels-hint-text" class="ScCoreLink-udwpw5-0 FXIKh tw-link" rel="noopener noreferrer" target="_blank" href="https://www.twitch.tv/nmplol">/nmplol</a></span> and <a data-test-selector="DropsCampaignInProgressDescription-multi-channels-hint-text" class="ScCoreLink-udwpw5-0 FXIKh tw-link" rel="noopener noreferrer" target="_blank" href="https://www.twitch.tv/malena">/malena</a></p>

**Comment by Zaarrg** [comment]
okay try this https://pastebin.com/sqUnah3J in mapdrops. this should fix it. let me know if it does

**Comment by Reserton** [comment]
Thanks, Fixed it!

![image](https://user-images.githubusercontent.com/1967737/126052604-83c5850b-4d53-4295-b0b0-56fdb41c66fd.png)

However I am now hitting Issue #21 lol.

There appears to be an issue with it thinking sykknuos drop is complete.

**Comment by Reserton** [comment]
As mentioned in issue 21 it could be because he has a previous drop as below : 

![image](https://user-images.githubusercontent.com/1967737/126052644-76d9191f-1de3-4575-b7e3-b5eb7177878f.png)

**Comment by Zaarrg** [comment]
Hm can u add `console.log(data.Streamers)` in src/checks checkifallclaimed in line around 7 and screenshot me what it logs in cmd

**Comment by Reserton** [comment]
Yeah shows claimed. Strange.

![image](https://user-images.githubusercontent.com/1967737/126052886-57441e17-0d78-49c0-8726-cea5bc786877.png)
![image](https://user-images.githubusercontent.com/1967737/126052893-49f6bbc0-2496-445c-80a0-048b1632f37b.png)

**Comment by Zaarrg** [comment]
Can u tell me if the claimed: true is actually true? Or tell me were it is wrong... Or is it only the sykkuno drop

**Comment by Reserton** [comment]
The false trues are : 

Ludwig
Nmplol
Sykkunno and
Sonii

My claimed drops are

Trainwrecks
Pokimane
Cyr
WillNeff
Myth
Arisaki

**Comment by Zaarrg** [comment]
Trying to recreate the error formyself but even after setting everything as u have it i dont get all live channels claimed....
Last thing hopefully can u log    ` console.log(data.claimed)` add this under the other log that u added

**Comment by Reserton** [comment]
Output is as below : 

`Watching https://www.twitch.tv/Sykkuno...

[
  {
    url: 'https://www.twitch.tv/Myth',
    live: false,
    name: 'Myth',
    drop: 'Myth Assault Rifle',
    claimed: true
  },
  {
    url: 'https://www.twitch.tv/Voyboy',
    live: false,
    name: 'Voyboy',
    drop: 'Voyboy Hammer',
    claimed: false
  },
  {
    url: 'https://www.twitch.tv/xQcOW',
    live: false,
    name: 'xQcOW',
    drop: 'xQc SAR',
    claimed: false
  },
  {
    url: 'https://www.twitch.tv/AriaSaki',
    live: true,
    name: 'AriaSaki',
    drop: 'Ariasaki Hammer',
    claimed: true
  },
  {
    url: 'https://www.twitch.tv/Sykkuno',
    live: true,
    name: 'Sykkuno',
    drop: 'Sykkuno Assault Rifle',
    claimed: true
  },
  {
    url: 'https://www.twitch.tv/ludwig',
    live: false,
    name: 'ludwig',
    drop: 'Ludwig Sleeping Bag',
    claimed: true
  },
  {
    url: 'https://www.twitch.tv/pokimane',
    live: false,
    name: 'pokimane',
    drop: 'Pokimane Painted Garage Door',
    claimed: true
  },
  {
    url: 'https://www.twitch.tv/Trainwreckstv',
    live: false,
    name: 'Trainwreckstv',
    drop: 'Trainwreckstv Combat Knife',
    claimed: true
  },
  {
    url: 'https://www.twitch.tv/Account Not Found',
    live: false,
    name: 'Account Not Found',
    drop: 'WillNeff Burlap Headwrap',
    claimed: true
  },
  {
    url: 'https://www.twitch.tv/Nmplol',
    live: false,
    name: 'Nmplol',
    drop: 'nmplol Chestplate',
    claimed: true
  },
  {
    url: 'https://www.twitch.tv/SONII',
    live: false,
    name: 'SONII',
    drop: 'Sonii Assault Rifle',
    claimed: true
  },
  {
    url: 'https://www.twitch.tv/cyr',
    live: false,
    name: 'cyr',
    drop: 'Cyr Burlap Shirt',
    claimed: true
  }
]
[
  'Pokimane Garage door',
  'Myth AK',
  'Trainwrecks Combat knife',
  'Ariasaki Building hammer',
  'Riqqeloff Rug',
  'WillNeff Headwrap',
  'Sinks Mp5',
  'Cyr Burlap Shirt',
  'KKatamina Facemask',
  'Frost M249',
  'xChocobars Large Box',
  'iitztimmy L96',
  'ShackyHD Armoured door ',
  'IOK Facemask',
  'Rpold Hoodie',
  'Golden Fan Weapon Charm',
  'Silver order — weaponry',
  'Reward pistol order',
  'Picco Jacket',
  'NoraExplorer Garage Door',
  'PyrooTv MP5',
  'Suspect Door of Glory',
  'etoleto SAR',
  'Tesla Rocket Launcher',
  '6zdenko Babushka Bandana',
  'xGuiRy Socks & Sandals',
  'DairyGold Fridge',
  'Shroud Pants',
  'Ricoy23 Garage Door',
  'Blooprint SAR',
  'iRiskpvp SAR',
  'deathwingua MP5',
  'Swales Facemask',
  'bnans Sleeping Bag',
  'r00t9r AR',
  'TwinkleCave Box',
  'Albin MP5',
  'Willjum Wolf Poncho',
  'Vice Hammer',
  'Lv. 57 Travel Kit',
  'DyannaTV Garage Door',
  'Trauzooka',
  'Ash_On_LoL Door',
  'Mammoth Armored Door',
  'JordanRants Jackpot Satchel',
  'bchillz SAR',
  'Killjoys Mask',
  'Buddha Mask',
  'PrinceVidz Hammer',
  'Posty BAR',
  'Welyn Garage Door',
  'Ray C. Double Door',
  'Coconut Rock',
  'Hutnik MP5',
  "Sequisha's Hot Dog Eoka",
  'Lifestomper MP5',
  "Mister Flak's Hammer",
  'hJune Jackhammer',
  'Pookie Hoodie',
  'Greekgodx Hunting Bow',
  'Pookie Pants',
  'ILLOJUAN Garage Door',
  'JuanSGuarnizo Chest Plate',
  'MoistCr1TiKaL Jacket',
  'Alexby Metal Door',
  'Aroyitt Garage Door',
  'Kitten Face Mask',
  'Mizkif Sleeping Bag',
  'Ornate Tempered Revolver',
  'Nebula Hoodie',
  'Rubius Crate',
  'Nebula Pants',
  'Sykkuno Longsleeve TShirt',
  'Jacksepticeye Storage',
  'Lilypichu Jacket',
  'Shroud Hoodie',
  'Pokimane Garage Door',
  'Ludwig Hoodie',
  'Myth Chestplate',
  'Hobo Barrel',
  'Industrial Door',
  'xQc Assault Rifle',
  'Sofa',
  'Magma Wings',
  'TwitchGlitch GlitchCon 2020 Emote',
  'Samurai2077 GlitchCon 2020 Emote',
  'KaWutGuys GlitchCon 2020 Emote',
  'FrankerCool GlitchCon 2020 Emote',
  'EnlightenD GlitchCon 2020 Emote',
  'AppaK GlitchCon 2020 Emote'
]

All live Channels claimed...`

**Comment by Zaarrg** [comment]
Okay finally recreated the error the bot acutally thinks that xQc Assault Rifle is Sykkuno Assault Rifle because its so similar, will have to fix it tomorrow as it already 4 a.m. 

**For now use one of those fixes:**
-The Check if the Drop is claimed is disabled, will add the feature after i fixed it.
- If using node:
Just Clone the repo and get the new version
- If using exe:
Download and replaced your ttvdropbot.exe with the one out of the TTVDropBot Temporarily Fixed.zip.
[TTVDropBot Temporarily Fixed.zip](https://github.com/Zaarrg/TTVDropBot/files/6835563/TTVDropBot.Temporarily.Fixed.zip)

**Comment by Reserton** [comment]
Perfect, that fixed it, thanks.

![image](https://user-images.githubusercontent.com/1967737/126054032-4427c375-0e58-4abc-981a-c03a0b75ee94.png)

**Comment by Reserton** [comment]
So for some reason when there is only live channels for ones I have the drops for, it still seems to want to wait for 3 trys. It then seems to hang waiting for a new stream.

As as below screenshot. Ludwig is now online and it hasn't picked it up. It has not changed for over an hour.

![image](https://user-images.githubusercontent.com/1967737/126055515-b8229a40-8d80-4bab-8399-634ab6e2dda6.png)

**Comment by Reserton** [comment]
I left it on overnight, and it got the NMP drop just fine. So I think the Ludwig one may have been a fluke due to it only being live 26 mins? not sure. 

The one stream bug still seems to be present though.

**Comment by Zaarrg** [comment]
Not quite sure if it is fixed in [1.3.3.1](https://github.com/Zaarrg/TTVDropBot/releases/tag/1.3.3.1), would be nice if you could check on it. Added a the Check if only one ch is live and it is already claimed/100% it will try to look every 10 mins for a new and it will loop thorugh the one ch which is live every 10 mins in this case nmplol because he was the only one live, im not quite sure wy it didn't watch ludwig after it was show as live have to look further into this bug

**Comment by Reserton** [comment]
Me and friend using the new version now. Will let you know if the issue reoccurs. Only Cyr streaming currently so good time to test.

The new chrome detect feature worked to find my .exe and the program accepted my profile path now too.

**Comment by Reserton** [comment]
Still happening unfortunatley : 

![image](https://user-images.githubusercontent.com/1967737/126078411-588c89ba-3dbc-4b8b-8513-0e274fbf8b11.png)

**Comment by Zaarrg** [comment]
Not active anymore, if this still occurs you can reopen this issue.
